/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 7.5 */
/* Mon Sep 28 11:44:29 2020 */

/* parameterized module instance */
ram_dpt_16x2k __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
